# Generated by Django 4.2.11 on 2024-03-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='origin',
            field=models.CharField(choices=[('air', 'Airbnb'), ('aus', 'Austin')], default='aus', max_length=3),
        ),
        migrations.AddField(
            model_name='reservation',
            name='uuid_external',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
