# Generated by Django 4.2.11 on 2024-04-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0005_alter_reservation_advance_payment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="tel_contact_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
