# Generated by Django 4.2.11 on 2024-04-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0006_reservation_tel_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="origin",
            field=models.CharField(
                choices=[
                    ("air", "Airbnb"),
                    ("aus", "Austin"),
                    ("man", "Mantenimiento"),
                ],
                default="aus",
                max_length=3,
            ),
        ),
    ]
