# Generated by Django 4.2.11 on 2024-04-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0008_reservation_full_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="price_sol",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="price_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
    ]
