# Generated by Django 4.2.11 on 2025-08-15 15:45

import apps.reservation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_reservation_manychatfecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='comentarios_reservas',
            field=models.TextField(blank=True, help_text='Comentarios adicionales sobre la reserva.', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fbc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fbclid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='fbp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ip_cliente',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='late_check_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='late_checkout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_confirmed',
            field=models.BooleanField(default=False, help_text='Indica si el cliente confirmó que realizó el pago'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_voucher_deadline',
            field=models.DateTimeField(blank=True, help_text='Fecha límite para subir voucher de pago (1 hora después de crear reserva)', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='payment_voucher_uploaded',
            field=models.BooleanField(default=False, help_text='Indica si el cliente ya subió el voucher de pago'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='points_redeemed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Puntos canjeados en esta reserva', max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='referer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incompleta'), ('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='incomplete', help_text='Estado de la reserva', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='utm_source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentalreceipt',
            name='file',
            field=models.FileField(upload_to=apps.reservation.models.recipt_directory_path),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='origin',
            field=models.CharField(choices=[('air', 'Airbnb'), ('aus', 'Austin'), ('man', 'Mantenimiento'), ('client', 'Cliente Web')], default='aus', max_length=6),
        ),
    ]
