# Generated by Django 4.2.11 on 2025-08-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0012_reservation_comentarios_reservas_reservation_fbc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='discount_code_used',
            field=models.CharField(blank=True, help_text='Código de descuento utilizado en esta reserva', max_length=20, null=True),
        ),
    ]
