# Generated by Django 4.2.11 on 2025-08-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0013_reservation_discount_code_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_approved_notification_sent',
            field=models.BooleanField(default=False, help_text='Indica si ya se envió la notificación de pago aprobado por WhatsApp'),
        ),
    ]
