# Generated by Django 4.2.11 on 2025-09-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0016_paymenttoken_amount_paymenttoken_reservation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price_latecheckout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Precio adicional por late checkout', max_digits=10, null=True),
        ),
    ]
