# Generated by Django 4.2.11 on 2025-09-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0018_add_price_latecheckout_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price_latecheckout',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Precio cobrado por late checkout (uso extendido del día de salida)', max_digits=10, null=True),
        ),
    ]
