# Generated by Django 4.2.11 on 2025-09-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0020_add_price_temperature_pool_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incompleta'), ('pending', 'Pendiente'), ('under_review', 'En Revisión - Segundo Voucher'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada')], default='incomplete', help_text='Estado de la reserva', max_length=15),
        ),
    ]
