# Generated by Django 4.2.11 on 2025-10-08 17:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_update_transaction_types'),
        ('reservation', '0021_add_under_review_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sesión activa')),
                ('host_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_music_sessions', to='clients.clients', verbose_name='Cliente anfitrión')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='music_session', to='reservation.reservation', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Sesión de Música',
                'verbose_name_plural': 'Sesiones de Música',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicSessionParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='Aceptado el')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='music_session_participations', to='clients.clients', verbose_name='Cliente participante')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='reservation.musicsession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Participante de Sesión de Música',
                'verbose_name_plural': 'Participantes de Sesiones de Música',
                'ordering': ['-accepted_at'],
                'unique_together': {('session', 'client')},
            },
        ),
    ]
