# Generated by Django 4.2.11 on 2025-09-14 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0041_latecheckoutconfig'),
        ('reservation', '0020_add_price_temperature_pool_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('staff_type', models.CharField(choices=[('cleaning', 'Limpieza'), ('maintenance', 'Mantenimiento'), ('both', 'Limpieza y Mantenimiento')], default='cleaning', max_length=20, verbose_name='Tipo de personal')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('vacation', 'De vacaciones'), ('sick', 'Incapacidad')], default='active', max_length=20, verbose_name='Estado')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='Foto del personal')),
                ('hire_date', models.DateField(verbose_name='Fecha de contratación')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa por hora')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('can_work_weekends', models.BooleanField(default=True, verbose_name='Puede trabajar fines de semana')),
                ('max_properties_per_day', models.PositiveIntegerField(default=3, verbose_name='Máximo de propiedades por día')),
                ('preferred_properties', models.ManyToManyField(blank=True, to='property.property', verbose_name='Propiedades preferidas')),
                ('user', models.OneToOneField(blank=True, help_text='Usuario del sistema (opcional)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('task_type', models.CharField(choices=[('checkout_cleaning', 'Limpieza post-checkout'), ('checkin_preparation', 'Preparación pre-checkin'), ('maintenance_repair', 'Reparación'), ('maintenance_preventive', 'Mantenimiento preventivo'), ('deep_cleaning', 'Limpieza profunda'), ('pool_maintenance', 'Mantenimiento de piscina'), ('garden_maintenance', 'Mantenimiento de jardín'), ('custom', 'Tarea personalizada')], max_length=30, verbose_name='Tipo de tarea')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la tarea')),
                ('description', models.TextField(blank=True, verbose_name='Descripción detallada')),
                ('scheduled_date', models.DateField(verbose_name='Fecha programada')),
                ('estimated_duration', models.DurationField(blank=True, help_text='Formato: HH:MM:SS', null=True, verbose_name='Duración estimada')),
                ('priority', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Prioridad')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('assigned', 'Asignada'), ('in_progress', 'En progreso'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('needs_review', 'Necesita revisión')], default='pending', max_length=20, verbose_name='Estado')),
                ('actual_start_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora real de inicio')),
                ('actual_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Hora real de finalización')),
                ('requires_photo_evidence', models.BooleanField(default=True, verbose_name='Requiere evidencia fotográfica')),
                ('completion_notes', models.TextField(blank=True, verbose_name='Notas de finalización')),
                ('supervisor_approved', models.BooleanField(default=False, verbose_name='Aprobado por supervisor')),
                ('building_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='Propiedad')),
                ('reservation', models.ForeignKey(blank=True, help_text='Solo para tareas de limpieza post-checkout', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.reservation', verbose_name='Reserva relacionada')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_tasks', to='staff.staffmember', verbose_name='Personal asignado')),
            ],
            options={
                'verbose_name': 'Tarea de trabajo',
                'verbose_name_plural': 'Tareas de trabajo',
                'ordering': ['scheduled_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='TimeTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('action_type', models.CharField(choices=[('check_in', 'Entrada'), ('check_out', 'Salida'), ('break_start', 'Inicio de descanso'), ('break_end', 'Fin de descanso')], max_length=20, verbose_name='Tipo de acción')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitud')),
                ('location_verified', models.BooleanField(default=False, verbose_name='Ubicación verificada')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='time_tracking_photos/', verbose_name='Foto de evidencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('building_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property', verbose_name='Propiedad')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_records', to='staff.staffmember', verbose_name='Personal')),
                ('work_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.worktask', verbose_name='Tarea relacionada')),
            ],
            options={
                'verbose_name': 'Registro de tiempo',
                'verbose_name_plural': 'Registros de tiempo',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('photo', models.ImageField(upload_to='task_photos/', verbose_name='Foto')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Subida el')),
                ('work_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='staff.worktask', verbose_name='Tarea')),
            ],
            options={
                'verbose_name': 'Foto de tarea',
                'verbose_name_plural': 'Fotos de tareas',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('schedule_type', models.CharField(choices=[('regular', 'Horario regular'), ('overtime', 'Tiempo extra'), ('on_call', 'Disponibilidad'), ('vacation', 'Vacaciones'), ('sick_leave', 'Incapacidad')], default='regular', max_length=20, verbose_name='Tipo de horario')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Hora de fin')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('notes', models.TextField(blank=True, verbose_name='Notas del día')),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='staff.staffmember', verbose_name='Personal')),
            ],
            options={
                'verbose_name': 'Horario de trabajo',
                'verbose_name_plural': 'Horarios de trabajo',
                'ordering': ['date'],
                'unique_together': {('staff_member', 'date')},
            },
        ),
    ]
