# Generated by Django 4.2.11 on 2025-09-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='staffmember',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa por día'),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de contratación'),
        ),
    ]
