# Generated by Django 4.2.11 on 2025-09-14 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_remove_staffmember_hourly_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktask',
            name='staff_member',
            field=models.ForeignKey(blank=True, help_text='Personal asignado a la tarea (puede estar sin asignar)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_tasks', to='staff.staffmember', verbose_name='Personal asignado'),
        ),
    ]
