# Generated by Django 4.2.11 on 2024-04-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0004_property_background_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="off_temperature_pool_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="on_temperature_pool_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
