# Generated by Django 4.2.11 on 2024-03-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_origin_reservation_uuid_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='uuid_external',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
