# Generated by Django 4.2.11 on 2024-04-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0003_alter_reservation_uuid_external"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="price_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
    ]
