# Generated by Django 4.2.11 on 2024-04-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservation", "0007_alter_reservation_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="full_payment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reservation",
            name="temperature_pool",
            field=models.BooleanField(default=False),
        ),
    ]
