# Generated by Django 4.2.11 on 2024-04-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0009_alter_reservation_price_sol_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="advance_payment",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=20, null=True
            ),
        ),
    ]
