version: "3"

services:
  db:
    image: mysql:8
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always

  config:
    build: .
    env_file:
      - .env
    volumes:
      - staticfiles:/code/staticfiles
      - .:/code
    depends_on:
      - db

  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - staticfiles:/code/staticfiles
    depends_on:
      - config

volumes:
  .:
  db_data:
  staticfiles: