# Generated by Django 4.2.11 on 2024-04-02 22:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0002_profitpropertyairbnb"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="profitpropertyairbnb",
            unique_together={("property", "month", "year")},
        ),
    ]
