# Generated by Django 4.2.11 on 2024-04-07 03:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenApiClients",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the instance was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The last time at the instance was modified.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="It can be set to false, usefull to simulate deletion",
                    ),
                ),
                ("token", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
