# Generated by Django 4.2.11 on 2024-04-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0002_tokenapiclients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tokenapiclients",
            name="token",
            field=models.CharField(max_length=250),
        ),
    ]
