# Generated by Django 4.2.11 on 2024-04-07 14:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0005_alter_clients_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tokenapiclients",
            options={
                "ordering": ["-created"],
                "verbose_name": "Token rutificador",
                "verbose_name_plural": "Tokens rutificadores",
            },
        ),
    ]
