# Generated by Django 4.2.11 on 2024-04-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0006_alter_tokenapiclients_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("dni", "Documento Nacional de Identidad"),
                    ("cex", "Carnet de Extranjeria"),
                    ("pas", "Pasaporte"),
                    ("run", "RUC"),
                ],
                default="dni",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="clients",
            name="first_name",
            field=models.CharField(default="nombre", max_length=30),
        ),
        migrations.AlterField(
            model_name="clients",
            name="number_doc",
            field=models.CharField(default="1", max_length=50),
        ),
    ]
