# Generated by Django 4.2.11 on 2024-04-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0008_alter_clients_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("m", "Masculino"), ("f", "Femenino")],
                default=None,
                max_length=1,
                null=True,
            ),
        ),
    ]
