# Generated by Django 4.2.11 on 2024-05-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0009_alter_clients_sex"),
    ]

    operations = [
        migrations.CreateModel(
            name="MensajeFidelidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "mensaje",
                    models.CharField(
                        help_text="Mensaje que se enviará a los clientes luego de saludarlos. Ej: Hola Augusto, --mensaje--",
                        max_length=255,
                    ),
                ),
            ],
        ),
    ]
