# Generated by Django 4.2.11 on 2024-06-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0010_mensajefidelidad"),
    ]

    operations = [
        migrations.AddField(
            model_name="clients",
            name="id_manychat",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clients",
            name="manychat",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
