# Generated by Django 4.2.11 on 2024-06-12 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_reservation_advance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ManychatFecha',
            field=models.IntegerField(default=0),
        ),
    ]
