# Generated by Django 4.2.11 on 2025-09-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='prize_description',
            field=models.CharField(blank=True, help_text='Descripción del premio ganado', max_length=200),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='winner_announcement_date',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se anunció como ganador', null=True),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='winner_notified',
            field=models.BooleanField(default=False, help_text='Si el ganador fue notificado por WhatsApp'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='winner_status',
            field=models.CharField(choices=[('not_winner', 'No ganador'), ('winner', '🏆 Ganador'), ('runner_up', '🥈 Segundo lugar'), ('third_place', '🥉 Tercer lugar')], default='not_winner', help_text='Estado del participante en el evento', max_length=15),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del evento (se convertirá automáticamente a WebP)', null=True, upload_to='events/'),
        ),
    ]
