# Generated by Django 4.2.11 on 2025-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration_prize_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Miniatura del evento (generada automáticamente)', null=True, upload_to='events/thumbnails/'),
        ),
    ]
