# Generated by Django 4.2.11 on 2025-09-16 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0041_latecheckoutconfig'),
        ('events', '0003_event_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='property_location',
            field=models.ForeignKey(blank=True, help_text='Propiedad asociada (solo para sorteos de estadías/noches gratis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='property.property', verbose_name='Propiedad'),
        ),
    ]
