# Generated by Django 4.2.11 on 2025-09-18 23:05

from django.db import migrations, models


def migrate_event_dates(apps, schema_editor):
    """Migrar start_date a event_date y hacer registration_deadline obligatorio"""
    Event = apps.get_model('events', 'Event')
    
    # Migrar todos los eventos existentes
    for event in Event.objects.all():
        # Usar start_date como event_date
        event.event_date = event.start_date
        # Si no tiene registration_deadline, usar start_date - 1 día como deadline
        if not event.registration_deadline:
            from django.utils import timezone
            from datetime import timedelta
            event.registration_deadline = event.start_date - timedelta(days=1)
        event.save()


def reverse_migrate_event_dates(apps, schema_editor):
    """Revertir migración si es necesario"""
    Event = apps.get_model('events', 'Event')
    
    for event in Event.objects.all():
        if event.event_date:
            event.start_date = event.event_date
            event.end_date = event.event_date  # Usar mismo valor para end_date
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_property_location'),
    ]

    operations = [
        # 1. Agregar campo event_date (nullable temporalmente)
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, help_text="Fecha y hora del sorteo/evento"),
        ),
        # 2. Migrar datos
        migrations.RunPython(migrate_event_dates, reverse_migrate_event_dates),
        # 3. Hacer event_date obligatorio
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(help_text="Fecha y hora del sorteo/evento"),
        ),
        # 4. Hacer registration_deadline obligatorio
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(help_text="Fecha límite para registrarse"),
        ),
        # 5. Eliminar campos antiguos
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
    ]