# Generated by Django 4.2.11 on 2025-09-20 00:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_options_activityfeed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityFeedConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('activity_type', models.CharField(choices=[('points_earned', 'Puntos Ganados'), ('reservation_made', 'Reserva Realizada'), ('event_created', 'Evento Creado'), ('event_registration', 'Registro a Evento'), ('event_winner', 'Ganador de Evento'), ('achievement_earned', 'Logro Obtenido'), ('property_visited', 'Propiedad Visitada'), ('payment_completed', 'Pago Completado'), ('discount_used', 'Descuento Utilizado'), ('review_posted', 'Reseña Publicada'), ('staff_assigned', 'Personal Asignado'), ('milestone_reached', 'Hito Alcanzado'), ('system_update', 'Actualización del Sistema')], help_text='Tipo de actividad a configurar', max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='¿Permitir que se generen automáticamente actividades de este tipo?')),
                ('is_public_by_default', models.BooleanField(default=True, help_text='¿Las actividades de este tipo deben ser públicas por defecto?')),
                ('default_importance_level', models.IntegerField(choices=[(1, 'Muy Baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Crítica')], default=2, help_text='Nivel de importancia por defecto para este tipo')),
                ('description', models.TextField(blank=True, help_text='Descripción de qué incluye este tipo de actividad')),
            ],
            options={
                'verbose_name': 'Configuración de Feed de Actividades',
                'verbose_name_plural': 'Configuraciones de Feed de Actividades',
                'ordering': ['activity_type'],
            },
        ),
    ]
