# Generated by Django 4.2.11 on 2025-09-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_activityfeedconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfeed',
            name='activity_type',
            field=models.CharField(choices=[('points_earned', 'Puntos Ganados'), ('reservation_made', 'Reserva Realizada'), ('reservation_auto_deleted_cron', 'Reserva Eliminada por Sistema'), ('client_registered', 'Cliente Registrado'), ('event_created', 'Evento Creado'), ('event_registration', 'Registro a Evento'), ('event_winner', 'Ganador de Evento'), ('achievement_earned', 'Logro Obtenido'), ('property_visited', 'Propiedad Visitada'), ('payment_completed', 'Pago Completado'), ('discount_used', 'Descuento Utilizado'), ('review_posted', 'Reseña Publicada'), ('staff_assigned', 'Personal Asignado'), ('milestone_reached', 'Hito Alcanzado'), ('system_update', 'Actualización del Sistema')], help_text='Tipo de actividad registrada', max_length=35),
        ),
        migrations.AlterField(
            model_name='activityfeedconfig',
            name='activity_type',
            field=models.CharField(choices=[('points_earned', 'Puntos Ganados'), ('reservation_made', 'Reserva Realizada'), ('reservation_auto_deleted_cron', 'Reserva Eliminada por Sistema'), ('client_registered', 'Cliente Registrado'), ('event_created', 'Evento Creado'), ('event_registration', 'Registro a Evento'), ('event_winner', 'Ganador de Evento'), ('achievement_earned', 'Logro Obtenido'), ('property_visited', 'Propiedad Visitada'), ('payment_completed', 'Pago Completado'), ('discount_used', 'Descuento Utilizado'), ('review_posted', 'Reseña Publicada'), ('staff_assigned', 'Personal Asignado'), ('milestone_reached', 'Hito Alcanzado'), ('system_update', 'Actualización del Sistema')], help_text='Tipo de actividad a configurar', max_length=35, unique=True),
        ),
    ]
