# Generated by Django 4.2.11 on 2025-09-20 08:01

from django.db import migrations, models


def remove_property_visited_activities(apps, schema_editor):
    """Eliminar todas las actividades de tipo property_visited"""
    ActivityFeed = apps.get_model('events', 'ActivityFeed')
    ActivityFeedConfig = apps.get_model('events', 'ActivityFeedConfig')
    
    # Eliminar actividades del feed
    deleted_activities = ActivityFeed.objects.filter(activity_type='property_visited').delete()
    print(f"Eliminadas {deleted_activities[0]} actividades de 'property_visited'")
    
    # Eliminar configuraciones si existen
    deleted_configs = ActivityFeedConfig.objects.filter(activity_type='property_visited').delete()
    print(f"Eliminadas {deleted_configs[0]} configuraciones de 'property_visited'")


def reverse_remove_property_visited_activities(apps, schema_editor):
    """Función de reversión - no hace nada ya que los datos se perdieron"""
    # No podemos recuperar los datos eliminados
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_update_activity_type_max_length'),
    ]

    operations = [
        # Primero eliminar los datos antes de cambiar el esquema
        migrations.RunPython(
            remove_property_visited_activities,
            reverse_remove_property_visited_activities,
        ),
        migrations.AlterField(
            model_name='activityfeed',
            name='activity_type',
            field=models.CharField(choices=[('points_earned', 'Puntos Ganados'), ('reservation_made', 'Reserva Realizada'), ('reservation_auto_deleted_cron', 'Reserva Eliminada por Sistema'), ('client_registered', 'Cliente Registrado'), ('event_created', 'Evento Creado'), ('event_registration', 'Registro a Evento'), ('event_winner', 'Ganador de Evento'), ('achievement_earned', 'Logro Obtenido'), ('payment_completed', 'Pago Completado'), ('discount_used', 'Descuento Utilizado'), ('review_posted', 'Reseña Publicada'), ('staff_assigned', 'Personal Asignado'), ('milestone_reached', 'Hito Alcanzado'), ('system_update', 'Actualización del Sistema')], help_text='Tipo de actividad registrada', max_length=35),
        ),
        migrations.AlterField(
            model_name='activityfeedconfig',
            name='activity_type',
            field=models.CharField(choices=[('points_earned', 'Puntos Ganados'), ('reservation_made', 'Reserva Realizada'), ('reservation_auto_deleted_cron', 'Reserva Eliminada por Sistema'), ('client_registered', 'Cliente Registrado'), ('event_created', 'Evento Creado'), ('event_registration', 'Registro a Evento'), ('event_winner', 'Ganador de Evento'), ('achievement_earned', 'Logro Obtenido'), ('payment_completed', 'Pago Completado'), ('discount_used', 'Descuento Utilizado'), ('review_posted', 'Reseña Publicada'), ('staff_assigned', 'Personal Asignado'), ('milestone_reached', 'Hito Alcanzado'), ('system_update', 'Actualización del Sistema')], help_text='Tipo de actividad a configurar', max_length=35, unique=True),
        ),
    ]
