# Generated by Django 4.2.11 on 2025-09-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_property_visited_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeedconfig',
            name='default_icon',
            field=models.CharField(blank=True, help_text='Emoji o icono por defecto para todas las actividades de este tipo', max_length=10),
        ),
    ]
