# Generated by Django 4.2.11 on 2025-09-21 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_add_default_icon_to_activityfeedconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityfeed',
            name='icon',
        ),
    ]
