# Generated by Django 4.2.11 on 2025-09-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_icon_from_activityfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeed',
            name='reason',
            field=models.CharField(blank=True, help_text="Motivo específico de la actividad (ej: 'voucher no subido en 60 minutos')", max_length=300),
        ),
    ]
