# Generated by Django 4.2.11 on 2025-09-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_add_reason_field_to_activityfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityfeedconfig',
            name='default_reason',
            field=models.CharField(blank=True, help_text="Motivo por defecto para actividades de este tipo (ej: 'voucher no subido en el plazo indicado')", max_length=300),
        ),
    ]
