# Generated by Django 4.2.11 on 2025-09-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_add_default_reason_to_activityfeedconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityfeed',
            name='reason',
        ),
    ]
