# Generated by Django 4.2.11 on 2025-09-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_activityfeed_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='winner_status',
            field=models.CharField(choices=[('not_winner', 'No ganador'), ('winner', '🏆 Ganador')], default='not_winner', help_text='Estado del participante en el evento', max_length=15),
        ),
    ]
