# Generated by Django 4.2.11 on 2025-09-23 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_update_winner_status_choices'),
    ]

    operations = [
    ]
