# Generated by Django 4.2.11 on 2025-09-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_convert_existing_winners'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_facebook_verification',
            field=models.BooleanField(default=False, help_text='Solo cuentas verificadas con Facebook pueden participar'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='winner_announcement_date',
            field=models.DateTimeField(blank=True, help_text='Fecha cuando se anunciará como ganador (se calcula automáticamente usando la fecha del evento)', null=True),
        ),
    ]
