# Generated by Django 4.2.11 on 2025-09-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_add_facebook_verification_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL amigable (se genera automáticamente)', max_length=250, null=True, unique=True),
        ),
    ]
