# Generated by Django 4.2.11 on 2025-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_add_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_evidence',
            field=models.BooleanField(default=False, help_text='Los participantes deben subir una foto/evidencia para participar'),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='evidence_image',
            field=models.ImageField(blank=True, help_text='Foto/evidencia requerida para participar (solo si el evento lo requiere)', null=True, upload_to='events/evidence/'),
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incompleto'), ('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado')], default='pending', max_length=15),
        ),
    ]
