# Generated by Django 4.2.11 on 2025-09-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_add_evidence_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contest_type',
            field=models.CharField(blank=True, choices=[('referral_count', 'Cantidad de Referidos'), ('referral_bookings', 'Reservas de Referidos')], help_text='Tipo de concurso (solo si is_contest=True)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='is_contest',
            field=models.BooleanField(default=False, help_text='Este evento es un concurso de referidos o reservas'),
        ),
    ]
