# Generated by Django 4.2.11 on 2025-09-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_add_contest_functionality'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_approved_reservation',
            field=models.BooleanField(default=True, help_text='Si se requiere tener al menos 1 reserva aprobada para participar'),
        ),
    ]
