# Generated by Django 4.2.11 on 2024-04-09 14:36

import apps.core.functions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to=apps.core.functions.user_directory_path,
            ),
        ),
    ]
