# Generated by Django 4.2.11 on 2024-04-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "clients",
            "0007_alter_clients_document_type_alter_clients_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("dni", "Documento Nacional de Identidad"),
                    ("cex", "Carnet de Extranjeria"),
                    ("pas", "Pasaporte"),
                    ("ruc", "RUC"),
                ],
                default="dni",
                max_length=3,
            ),
        ),
    ]
