# Generated by Django 4.2.11 on 2024-04-02 21:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfitPropertyAirBnb",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the instance was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The last time at the instance was modified.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "deleted",
                    models.BooleanField(
                        default=False,
                        help_text="It can be set to false, usefull to simulate deletion",
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("year", models.PositiveIntegerField(default=1)),
                (
                    "profit_sol",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Ganancia (Soles)"
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="property.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
