# Generated by Django 4.2.11 on 2024-04-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("property", "0003_alter_profitpropertyairbnb_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="background_color",
            field=models.CharField(default="#fff", max_length=255),
        ),
    ]
