
# Generated by Django 4.2.7 on 2024-01-15 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_add_slug_field_safely'),
    ]

    operations = [
        # Primero eliminamos cualquier constraint existente de forma segura
        migrations.RunSQL(
            """
            SELECT CONCAT('ALTER TABLE property_propertyphoto DROP FOREIGN KEY ', CONSTRAINT_NAME, ';') AS query
            FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'property_propertyphoto' 
            AND COLUMN_NAME = 'property_id' 
            AND CONSTRAINT_NAME != 'PRIMARY';
            """,
            reverse_sql="-- No reverse needed"
        ),
        
        # Ejecutar el DROP si existe constraint
        migrations.RunSQL(
            """
            SET @sql = (
                SELECT CONCAT('ALTER TABLE property_propertyphoto DROP FOREIGN KEY ', CONSTRAINT_NAME)
                FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'property_propertyphoto' 
                AND COLUMN_NAME = 'property_id' 
                AND CONSTRAINT_NAME != 'PRIMARY'
                LIMIT 1
            );
            
            SET @sql = IFNULL(@sql, 'SELECT "No foreign key to drop" as info');
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="-- No reverse needed"
        ),
        
        # Cambiar el tipo de columna property_id para que coincida con Property.id
        migrations.RunSQL(
            "ALTER TABLE property_propertyphoto MODIFY COLUMN property_id CHAR(32) NOT NULL;",
            reverse_sql="ALTER TABLE property_propertyphoto MODIFY COLUMN property_id INT NOT NULL;"
        ),
        
        # Agregar nuevo constraint de clave externa
        migrations.RunSQL(
            "ALTER TABLE property_propertyphoto ADD CONSTRAINT property_propertyphoto_property_id_fk FOREIGN KEY (property_id) REFERENCES property_property (id) ON DELETE CASCADE;",
            reverse_sql="ALTER TABLE property_propertyphoto DROP FOREIGN KEY property_propertyphoto_property_id_fk;"
        ),
        
        # Actualizar el modelo para usar el ForeignKey correcto
        migrations.AlterField(
            model_name='propertyphoto',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='property.property'),
        ),
    ]
