
# Generated by Django 4.2.7 on 2024-01-15 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_add_slug_field_safely'),
    ]

    operations = [
        # Solo modificar el tipo de columna property_id sin tocar constraints
        migrations.RunSQL(
            "ALTER TABLE property_propertyphoto MODIFY COLUMN property_id CHAR(32) NOT NULL;",
            reverse_sql="ALTER TABLE property_propertyphoto MODIFY COLUMN property_id INT NOT NULL;"
        ),

        # Agregar nuevo constraint de clave externa si no existe ya
        migrations.RunSQL(
            """
            SELECT COUNT(*) INTO @constraint_exists 
            FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'property_propertyphoto' 
            AND COLUMN_NAME = 'property_id' 
            AND CONSTRAINT_NAME = 'property_propertyphoto_property_id_fk';
            
            SET @sql = IF(@constraint_exists = 0,
                'ALTER TABLE property_propertyphoto ADD CONSTRAINT property_propertyphoto_property_id_fk FOREIGN KEY (property_id) REFERENCES property_property (id) ON DELETE CASCADE',
                'SELECT "Constraint already exists" as info'
            );
            
            PREPARE stmt FROM @sql;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE property_propertyphoto DROP FOREIGN KEY property_propertyphoto_property_id_fk;"
        ),
    ]
