# Generated by Django 4.2.7 on 2024-01-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_add_slug_field_safely'),
    ]

    operations = [
        # Paso 1: Eliminar cualquier restricción existente
        migrations.RunSQL(
            """
            ALTER TABLE property_propertyphoto DROP FOREIGN KEY IF EXISTS property_propertyphoto_property_id_fk;
            """,
            reverse_sql="-- No reverse needed"
        ),

        # Paso 2: Modificar property_id para que sea exactamente igual que property.id
        migrations.RunSQL(
            """
            ALTER TABLE property_propertyphoto 
            MODIFY COLUMN property_id CHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL;
            """,
            reverse_sql="ALTER TABLE property_propertyphoto MODIFY COLUMN property_id INT NOT NULL;"
        ),

        # Paso 3: Recrear la foreign key
        migrations.RunSQL(
            """
            ALTER TABLE property_propertyphoto 
            ADD CONSTRAINT property_propertyphoto_property_id_fk 
            FOREIGN KEY (property_id) REFERENCES property_property (id) 
            ON DELETE CASCADE;
            """,
            reverse_sql="ALTER TABLE property_propertyphoto DROP FOREIGN KEY property_propertyphoto_property_id_fk;"
        ),
    ]