# Generated by Django 4.2.11 on 2025-08-15 15:45

import apps.property.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_fix_property_photo_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='banos',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de baños'),
        ),
        migrations.AddField(
            model_name='property',
            name='caracteristicas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de características de la propiedad', verbose_name='Características'),
        ),
        migrations.AddField(
            model_name='property',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='property',
            name='detalle_dormitorios',
            field=models.JSONField(blank=True, default=dict, help_text='JSON con detalles de cada habitación', verbose_name='Detalle de dormitorios'),
        ),
        migrations.AddField(
            model_name='property',
            name='dormitorios',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de dormitorios'),
        ),
        migrations.AddField(
            model_name='property',
            name='hora_ingreso',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de ingreso'),
        ),
        migrations.AddField(
            model_name='property',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de salida'),
        ),
        migrations.AddField(
            model_name='property',
            name='precio_desde',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio base de referencia para mostrar en listados', max_digits=10, null=True, verbose_name='Precio desde'),
        ),
        migrations.AddField(
            model_name='property',
            name='precio_extra_persona',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio extra por persona'),
        ),
        migrations.AddField(
            model_name='property',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL de la imagen')),
                ('image_file', models.ImageField(blank=True, help_text='Tamaño máximo: 20MB. Formatos permitidos: JPG, PNG, GIF', null=True, upload_to=apps.property.models.property_photo_upload_path, validators=[apps.property.models.validate_image_size], verbose_name='Archivo de imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Texto alternativo')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización (0 = primera)', verbose_name='Orden')),
                ('is_main', models.BooleanField(default=False, verbose_name='Imagen principal')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='property.property')),
            ],
            options={
                'verbose_name': 'Foto de Propiedad',
                'verbose_name_plural': 'Fotos de Propiedades',
                'ordering': ['order'],
            },
        ),
    ]
