# Generated by Django 4.2.11 on 2025-08-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_automaticdiscount_exchangerate_seasonpricing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalservice',
            name='properties',
        ),
        migrations.DeleteModel(
            name='AutomaticDiscount',
        ),
        migrations.RemoveField(
            model_name='cancellationpolicy',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='discountcode',
            name='properties',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.RemoveField(
            model_name='seasonpricing',
            name='property',
        ),
        migrations.DeleteModel(
            name='AdditionalService',
        ),
        migrations.DeleteModel(
            name='CancellationPolicy',
        ),
        migrations.DeleteModel(
            name='DiscountCode',
        ),
        migrations.DeleteModel(
            name='SeasonPricing',
        ),
    ]
