# Generated by Django 4.2.11 on 2025-08-15 17:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_automaticdiscount_exchangerate_seasonpricing_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonpricing',
            options={'ordering': ['property', 'start_date'], 'verbose_name': '📅 Temporada', 'verbose_name_plural': '📅 Temporadas'},
        ),
        migrations.RemoveField(
            model_name='seasonpricing',
            name='multiplier',
        ),
        migrations.RemoveField(
            model_name='seasonpricing',
            name='price_usd',
        ),
        migrations.AlterField(
            model_name='property',
            name='precio_extra_persona',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio que se cobra por cada persona adicional después de la primera, por noche', max_digits=10, null=True, verbose_name='Precio extra por persona adicional (después de la 1ra persona)'),
        ),
        migrations.AlterField(
            model_name='seasonpricing',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='property.property'),
        ),
        migrations.AlterField(
            model_name='seasonpricing',
            name='season_type',
            field=models.CharField(choices=[('low', 'Temporada Baja'), ('high', 'Temporada Alta')], max_length=4),
        ),
        migrations.CreateModel(
            name='PropertyPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('weekday_low_season_usd', models.DecimalField(decimal_places=2, default=0, help_text='Precio base por noche de día de semana en temporada baja (Lunes-Jueves) en USD para 1 persona', max_digits=10)),
                ('weekend_low_season_usd', models.DecimalField(decimal_places=2, default=0, help_text='Precio base por noche de fin de semana en temporada baja (Viernes-Domingo) en USD para 1 persona', max_digits=10)),
                ('weekday_high_season_usd', models.DecimalField(decimal_places=2, default=0, help_text='Precio base por noche de día de semana en temporada alta (Lunes-Jueves) en USD para 1 persona', max_digits=10)),
                ('weekend_high_season_usd', models.DecimalField(decimal_places=2, default=0, help_text='Precio base por noche de fin de semana en temporada alta (Viernes-Domingo) en USD para 1 persona', max_digits=10)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='property.property')),
            ],
            options={
                'verbose_name': '💰 Precio Base de Propiedad',
                'verbose_name_plural': '💰 Precios Base de Propiedades',
            },
        ),
        migrations.CreateModel(
            name='SpecialDatePricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('date', models.DateField(help_text='Fecha específica (ej: 2024-12-31)')),
                ('description', models.CharField(help_text='Descripción del día especial (ej: Año Nuevo, Navidad)', max_length=100)),
                ('price_usd', models.DecimalField(decimal_places=2, help_text='Precio base especial por noche en USD para 1 persona', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_date_pricing', to='property.property')),
            ],
            options={
                'verbose_name': '🎉 Precio Fecha Especial',
                'verbose_name_plural': '🎉 Precios Fechas Especiales',
                'ordering': ['property', 'date'],
                'unique_together': {('property', 'date')},
            },
        ),
    ]
