# Generated by Django 4.2.11 on 2025-08-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_seasonpricing_options_and_more'),
    ]

    operations = [
    ]
