# Generated by Django 4.2.11 on 2025-08-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_add_name_field_with_default'),
        ('property', '0016_auto_20250815_1744'),
    ]

    operations = [
    ]
