# Generated by Django 4.2.11 on 2025-08-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_merge_20250815_1745'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonpricing',
            options={'ordering': ['start_date'], 'verbose_name': '📅 Temporada Global', 'verbose_name_plural': '📅 Temporadas Globales'},
        ),
        migrations.RemoveField(
            model_name='seasonpricing',
            name='property',
        ),
    ]
