# Generated by Django 4.2.11 on 2025-08-15 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_seasonpricing_recurrent_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonpricing',
            name='end_day',
            field=models.PositiveIntegerField(help_text='Día de fin (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='seasonpricing',
            name='end_month',
            field=models.PositiveIntegerField(help_text='Mes de fin (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='seasonpricing',
            name='name',
            field=models.CharField(help_text="Nombre de la temporada (ej: 'Verano', 'Navidad y Año Nuevo', 'Fiestas Patrias')", max_length=100),
        ),
        migrations.AlterField(
            model_name='seasonpricing',
            name='start_day',
            field=models.PositiveIntegerField(help_text='Día de inicio (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='seasonpricing',
            name='start_month',
            field=models.PositiveIntegerField(help_text='Mes de inicio (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
