# Generated by Django 4.2.11 on 2025-08-15 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_convert_special_dates_to_recurrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdatepricing',
            name='day',
            field=models.PositiveIntegerField(help_text='Día de la fecha especial (1-31)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AlterField(
            model_name='specialdatepricing',
            name='description',
            field=models.CharField(help_text='Descripción del día especial (ej: Año Nuevo, Navidad, Día de la Madre)', max_length=100),
        ),
        migrations.AlterField(
            model_name='specialdatepricing',
            name='month',
            field=models.PositiveIntegerField(help_text='Mes de la fecha especial (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
