# Generated by Django 4.2.11 on 2025-08-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_alter_specialdatepricing_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialdatepricing',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción del día especial (ej: Año Nuevo, Navidad, Día de la Madre)', max_length=100, null=True),
        ),
    ]
