# Generated by Django 4.2.11 on 2025-08-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0023_alter_specialdatepricing_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='restrict_weekdays',
            field=models.BooleanField(default=False, help_text='Restringir solo a noches de semana (domingo a jueves)'),
        ),
        migrations.AddField(
            model_name='discountcode',
            name='restrict_weekends',
            field=models.BooleanField(default=False, help_text='Restringir solo a noches de fin de semana (viernes y sábado)'),
        ),
    ]
