# Generated by Django 4.2.11 on 2025-08-16 09:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0024_discountcode_restrict_weekdays_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDiscountConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('name', models.CharField(help_text='Nombre de la configuración', max_length=100)),
                ('prefix', models.CharField(help_text='Prefijo para los códigos generados (ej: PROMO)', max_length=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('validity_days', models.PositiveIntegerField(default=7, help_text='Días de validez desde la creación del código')),
                ('min_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='Monto mínimo en USD para aplicar descuento', max_digits=10)),
                ('max_discount_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento máximo en USD', max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(default=1, help_text='Límite de usos por código generado')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '⚡ Generador de Códigos Dinámicos',
                'verbose_name_plural': '⚡ Generadores de Códigos Dinámicos',
            },
        ),
        migrations.AlterModelOptions(
            name='automaticdiscount',
            options={'verbose_name': '🤖 Descuento Automático', 'verbose_name_plural': '🤖 Descuentos Automáticos'},
        ),
    ]
