# Generated by Django 4.2.11 on 2025-08-18 08:10

import apps.property.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_dynamicdiscountconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Imagen optimizada para cards, generada automáticamente', null=True, upload_to=apps.property.models.property_photo_upload_path, verbose_name='Thumbnail (400x300)'),
        ),
    ]
