# Generated by Django 4.2.11 on 2025-08-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_add_minimum_consecutive_nights'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticdiscount',
            name='restrict_weekdays',
            field=models.BooleanField(default=False, help_text='Si está activo, el descuento solo aplica para días de semana (Lunes a Viernes)'),
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='restrict_weekends',
            field=models.BooleanField(default=False, help_text='Si está activo, el descuento solo aplica para fines de semana (Sábado y Domingo)'),
        ),
    ]
