# Generated by Django 4.2.11 on 2025-08-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_achievement_clientachievement'),
        ('property', '0030_automaticdiscount_restrict_weekdays_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automaticdiscount',
            name='min_reservations',
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='required_achievements',
            field=models.ManyToManyField(blank=True, help_text='Logros requeridos para aplicar este descuento automático', to='clients.achievement'),
        ),
    ]
