
# Generated by Django 4.2.11 on 2025-08-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0034_cleanup_migration_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticdiscount',
            name='trigger',
            field=models.CharField(choices=[('birthday', 'Mes de Cumpleaños'), ('returning', 'Cliente Recurrente'), ('first_time', 'Primera Reserva'), ('loyalty', 'Programa de Lealtad'), ('last_minute', 'Último Minuto')], max_length=20),
        ),
    ]
