# Generated by Django 4.2.11 on 2025-09-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0035_increase_trigger_field_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticdiscount',
            name='trigger',
            field=models.CharField(choices=[('birthday', 'Mes de Cumpleaños'), ('returning', 'Cliente Recurrente'), ('first_time', 'Primera Reserva'), ('loyalty', 'Programa de Lealtad'), ('last_minute', 'Último Minuto'), ('global_promotion', 'Promoción Global')], max_length=20),
        ),
    ]
