# Generated by Django 4.2.11 on 2025-09-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0036_alter_automaticdiscount_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticdiscount',
            name='end_date',
            field=models.DateField(blank=True, help_text='Fecha de fin de validez del descuento (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='automaticdiscount',
            name='start_date',
            field=models.DateField(blank=True, help_text='Fecha de inicio de validez del descuento (opcional)', null=True),
        ),
    ]
