# Generated by Django 4.2.11 on 2025-09-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0037_add_date_validity_to_automatic_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticdiscount',
            name='apply_only_to_base_price',
            field=models.BooleanField(default=False, help_text='Si está activo, el descuento solo se aplica al precio base (sin incluir huéspedes adicionales)'),
        ),
        migrations.AlterField(
            model_name='automaticdiscount',
            name='trigger',
            field=models.CharField(choices=[('birthday', 'Mes de Cumpleaños'), ('returning', 'Cliente Recurrente'), ('first_time', 'Primera Reserva'), ('loyalty', 'Programa de Lealtad'), ('last_minute', 'Último Minuto'), ('global_promotion', 'Promoción Global'), ('base_price_discount', 'Descuento Solo Precio Base')], max_length=20),
        ),
    ]
