# Generated by Django 4.2.11 on 2025-09-08 14:33

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0040_add_post_action_to_additionalservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='LateCheckoutConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de configuración')),
                ('weekday', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día de la semana')),
                ('allows_late_checkout', models.BooleanField(default=True, verbose_name='Permite late checkout')),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje'), ('fixed', 'Monto fijo')], default='percentage', max_length=10, verbose_name='Tipo de descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10, verbose_name='Valor del descuento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Configuración de Late Checkout',
                'verbose_name_plural': 'Configuraciones de Late Checkout',
                'unique_together': {('weekday',)},
            },
        ),
    ]
