# Generated by Django 4.2.11 on 2025-10-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0041_latecheckoutconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='automaticdiscount',
            name='specific_weekdays',
            field=models.CharField(blank=True, help_text="Días específicos de la semana (0=Lun,1=Mar,2=Mié,3=Jue,4=Vie,5=Sáb,6=Dom). Ej: '4' para solo Viernes, '4,5' para Viernes y Sábado", max_length=20, null=True),
        ),
    ]
