# Generated by Django 4.2.11 on 2025-10-06 22:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_update_transaction_types'),
        ('property', '0042_add_specific_weekdays_to_automatic_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralDiscountByLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento para primera reserva del referido (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True, help_text='Activar/desactivar este descuento')),
                ('achievement', models.ForeignKey(help_text='Nivel/Logro del cliente que refiere', on_delete=django.db.models.deletion.CASCADE, to='clients.achievement')),
            ],
            options={
                'verbose_name': 'Descuento de Referido por Nivel',
                'verbose_name_plural': 'Descuentos de Referidos por Nivel',
                'ordering': ['achievement__order', 'achievement__required_reservations'],
                'unique_together': {('achievement',)},
            },
        ),
    ]
