# Generated by Django 4.2.11 on 2025-10-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0043_referraldiscountbylevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automaticdiscount',
            name='trigger',
            field=models.CharField(choices=[('birthday', 'Mes de Cumpleaños'), ('returning', 'Cliente Frecuente'), ('first_time', 'Primera Reserva'), ('loyalty', 'Programa de Lealtad'), ('last_minute', 'Último Minuto'), ('global_promotion', 'Promoción Global')], max_length=20),
        ),
    ]
