# Generated by Django 4.2.11 on 2025-10-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0044_alter_automaticdiscount_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='player_id',
            field=models.CharField(blank=True, help_text='ID del reproductor de Music Assistant vinculado a esta propiedad', max_length=100, null=True, verbose_name='ID del Reproductor Music Assistant'),
        ),
    ]
