# Generated by Django 4.2.11 on 2025-10-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0045_property_player_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='player_id',
            field=models.CharField(blank=True, help_text='ID de la casa (1-4) para el sistema de música', max_length=100, null=True, verbose_name='ID de Casa'),
        ),
    ]
