# Generated by Django 4.2.11 on 2025-10-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0047_convert_player_id_to_house_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='player_id',
            field=models.CharField(blank=True, help_text='Escribe el ID de la casa (ej: ca1, ca2, ca3, ca4)', max_length=50, null=True, verbose_name='ID de Casa'),
        ),
    ]
