# Generated by Django 4.2.11 on 2025-11-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0048_remove_house_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='apply_only_to_base_price',
            field=models.BooleanField(default=False, help_text='Si está activo, el descuento solo se aplica al precio base (sin incluir huéspedes adicionales)'),
        ),
        migrations.AddField(
            model_name='dynamicdiscountconfig',
            name='apply_only_to_base_price',
            field=models.BooleanField(default=False, help_text='Si está activo, los códigos generados solo se aplicarán al precio base (sin incluir huéspedes adicionales)'),
        ),
    ]
