# Generated by Django 4.2.11 on 2025-11-05 10:49

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0049_add_apply_only_to_base_price_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeDiscountConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('name', models.CharField(default='Descuento de Bienvenida', help_text='Nombre descriptivo de la configuración', max_length=200)),
                ('is_active', models.BooleanField(default=False, help_text='Si está activo, los nuevos usuarios registrados recibirán este descuento')),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje de descuento (ej: 15.00 para 15%)', max_digits=5)),
                ('validity_days', models.PositiveIntegerField(default=14, help_text='Días de validez del código desde su emisión')),
                ('min_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monto mínimo de reserva en USD para aplicar el descuento', max_digits=10)),
                ('max_discount_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Descuento máximo en USD (opcional)', max_digits=10, null=True)),
                ('restrict_weekdays', models.BooleanField(default=False, help_text='Restringir solo a noches de semana (domingo a jueves)')),
                ('restrict_weekends', models.BooleanField(default=False, help_text='Restringir solo a noches de fin de semana (viernes y sábado)')),
                ('apply_only_to_base_price', models.BooleanField(default=False, help_text='Si está activo, el descuento solo se aplica al precio base (sin incluir huéspedes adicionales)')),
                ('properties', models.ManyToManyField(blank=True, help_text='Propiedades donde será válido el descuento (vacío = todas)', to='property.property')),
            ],
            options={
                'verbose_name': '🎁 Configuración de Descuento de Bienvenida',
                'verbose_name_plural': '🎁 Configuraciones de Descuento de Bienvenida',
            },
        ),
    ]
