# Generated by Django 4.2.11 on 2025-11-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0050_welcomediscountconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomediscountconfig',
            name='promotional_message',
            field=models.CharField(blank=True, help_text="Mensaje personalizado para mostrar en la web (ej: '¡Regístrate hoy y recibe 15% OFF!'). Si está vacío, se genera automáticamente.", max_length=500, null=True),
        ),
    ]
