# Generated by Django 4.2.11 on 2025-11-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0051_add_promotional_message_to_welcome_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcomediscountconfig',
            name='promotional_subtitle',
            field=models.CharField(blank=True, help_text="Texto adicional en letras pequeñas (ej: 'Válido solo para reservas de 3+ noches' o 'No aplica en días festivos')", max_length=300, null=True),
        ),
    ]
