# Generated by Django 4.2.11 on 2025-11-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0052_add_promotional_subtitle_to_welcome_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='code',
            field=models.CharField(help_text='Código de descuento', max_length=50, unique=True),
        ),
    ]
