# Generated by Django 4.2.11 on 2025-11-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0053_increase_discount_code_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicdiscountconfig',
            name='restrict_weekdays',
            field=models.BooleanField(default=False, help_text='Si está activo, los códigos generados solo serán válidos para noches de semana (domingo a jueves)'),
        ),
        migrations.AddField(
            model_name='dynamicdiscountconfig',
            name='restrict_weekends',
            field=models.BooleanField(default=False, help_text='Si está activo, los códigos generados solo serán válidos para fines de semana (viernes y sábado)'),
        ),
    ]
