# Generated by Django 4.2.11 on 2025-11-22 01:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0055_add_specific_weekdays_to_welcome_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAssistantDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('entity_id', models.CharField(help_text='Entity ID del dispositivo en Home Assistant (ej: light.sala_principal)', max_length=200)),
                ('friendly_name', models.CharField(help_text='Nombre amigable para mostrar al usuario (ej: Luz Principal)', max_length=200)),
                ('device_type', models.CharField(choices=[('light', 'Luz'), ('climate', 'Clima/Calefacción'), ('switch', 'Interruptor'), ('cover', 'Cortina/Persiana'), ('scene', 'Escena'), ('fan', 'Ventilador'), ('media_player', 'Reproductor Multimedia'), ('lock', 'Cerradura'), ('camera', 'Cámara'), ('sensor', 'Sensor'), ('other', 'Otro')], default='light', help_text='Tipo de dispositivo', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Emoji o ícono para mostrar (ej: 💡, 🌡️, 🔌)', max_length=50, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Orden de visualización (menor número = más arriba)')),
                ('guest_accessible', models.BooleanField(default=True, help_text='¿Los huéspedes pueden controlar este dispositivo?')),
                ('is_active', models.BooleanField(default=True, help_text='¿Este dispositivo está activo?')),
                ('device_config', models.JSONField(blank=True, default=dict, help_text='Configuración adicional específica del tipo de dispositivo')),
                ('description', models.TextField(blank=True, help_text='Descripción o instrucciones para el huésped', null=True)),
                ('property', models.ForeignKey(help_text='Propiedad a la que pertenece este dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='homeassistant_devices', to='property.property')),
            ],
            options={
                'verbose_name': 'Dispositivo de Home Assistant',
                'verbose_name_plural': 'Dispositivos de Home Assistant',
                'ordering': ['property', 'display_order', 'friendly_name'],
                'unique_together': {('property', 'entity_id')},
            },
        ),
    ]
