# Generated by Django 4.2.11 on 2025-11-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0056_homeassistantdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeassistantdevice',
            name='location',
            field=models.CharField(blank=True, help_text='Ubicación del dispositivo para agrupar en el frontend (ej: 2do Piso, Área Piscina, Sala Principal)', max_length=100, null=True),
        ),
    ]
