# Generated by Django 4.2.11 on 2024-03-22 15:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('document_type', models.CharField(choices=[('dni', 'Documento Nacional de Identidad'), ('cex', 'Carnet de Extranjeria'), ('pas', 'Pasaporte')], default='dni', max_length=3, null=True)),
                ('number_doc', models.CharField(max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de Nacimiento', verbose_name='Nacimiento')),
                ('sex', models.CharField(choices=[('m', 'Masculino'), ('f', 'Femenino')], default='f', max_length=1)),
                ('email', models.EmailField(max_length=150)),
                ('date', models.DateField()),
                ('tel_number', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
