# Generated by Django 4.2.11 on 2024-03-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='fecha_nacimiento',
        ),
    ]
