# Generated by Django 4.2.11 on 2024-04-07 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_alter_tokenapiclients_token"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clients",
            unique_together={("document_type", "number_doc")},
        ),
    ]
