# Generated by Django 4.2.11 on 2024-04-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0004_alter_clients_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="email",
            field=models.EmailField(blank=True, max_length=150, null=True),
        ),
    ]
