
# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_clients_id_manychat_clients_manychat'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Código de referido único y corto', max_length=8, null=True, unique=True),
        ),
    ]
