# Generated by Django 4.2.11 on 2025-08-18 09:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_referralpointsconfig_clients_comentarios_clientes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('name', models.CharField(help_text='Nombre del logro', max_length=100)),
                ('description', models.TextField(help_text='Descripción del logro')),
                ('icon', models.CharField(blank=True, help_text='Emoji o icono del logro', max_length=50, null=True)),
                ('required_reservations', models.PositiveIntegerField(default=0, help_text='Número mínimo de reservas requeridas')),
                ('required_referrals', models.PositiveIntegerField(default=0, help_text='Número mínimo de referidos requeridos')),
                ('required_referral_reservations', models.PositiveIntegerField(default=0, help_text='Número mínimo de reservas de referidos requeridas')),
                ('is_active', models.BooleanField(default=True, help_text='Activar/desactivar este logro')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['order', 'required_reservations', 'required_referrals'],
            },
        ),
        migrations.CreateModel(
            name='ClientAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('earned_at', models.DateTimeField(auto_now_add=True, help_text='Fecha cuando se obtuvo el logro')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.achievement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='clients.clients')),
            ],
            options={
                'verbose_name': 'Logro de Cliente',
                'verbose_name_plural': 'Logros de Clientes',
                'ordering': ['-earned_at'],
                'unique_together': {('client', 'achievement')},
            },
        ),
    ]
