# Generated by Django 4.2.11 on 2025-08-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0014_achievement_clientachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
