# Generated by Django 4.2.11 on 2025-09-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_alter_clients_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchtracking',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Dirección IP del usuario', null=True),
        ),
        migrations.AddField(
            model_name='searchtracking',
            name='referrer',
            field=models.URLField(blank=True, help_text='URL de referencia', null=True),
        ),
        migrations.AddField(
            model_name='searchtracking',
            name='session_key',
            field=models.CharField(blank=True, help_text='Clave de sesión para usuarios anónimos', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchtracking',
            name='user_agent',
            field=models.TextField(blank=True, help_text='User agent del navegador', null=True),
        ),
        migrations.AlterField(
            model_name='searchtracking',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Cliente que realiza la búsqueda (null para usuarios anónimos)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_tracking', to='clients.clients'),
        ),
    ]
