# Generated by Django 4.2.11 on 2025-09-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0016_searchtracking_ip_address_searchtracking_referrer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='facebook_id',
            field=models.CharField(blank=True, help_text='ID único de Facebook del usuario', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='facebook_linked_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se vinculó la cuenta de Facebook', null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='facebook_profile_data',
            field=models.JSONField(blank=True, help_text='Datos del perfil de Facebook (nombre, foto, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='facebook_verified',
            field=models.BooleanField(default=False, help_text='Indica si el cliente ha verificado su cuenta con Facebook (check azul)'),
        ),
    ]
