# Generated by Django 4.2.11 on 2025-09-18 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0017_add_facebook_oauth_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='facebook_verified',
        ),
        migrations.AddField(
            model_name='clients',
            name='facebook_linked',
            field=models.BooleanField(default=False, help_text='Indica si el cliente ha vinculado su cuenta de Facebook'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='facebook_id',
            field=models.CharField(blank=True, help_text='ID único de Facebook del usuario', max_length=100, null=True),
        ),
    ]
