# Generated by Django 2.11 on 2025-09-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0018_update_facebook_field_names'),
    ]

    operations = [
        # Agregar constraint único con Django ORM (cross-database compatible)  
        migrations.AddConstraint(
            model_name='clients',
            constraint=models.UniqueConstraint(
                fields=['facebook_id'],
                condition=models.Q(deleted=False, facebook_id__isnull=False),
                name='clients_fb_id_unique_not_deleted'
            ),
        ),
    ]
