# Generated by Django 4.2.11 on 2025-09-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0019_add_facebook_id_unique_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clients',
            name='clients_fb_id_unique_not_deleted',
        ),
    ]
