# Generated by Django 4.2.11 on 2025-09-23 14:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0020_remove_clients_clients_fb_id_unique_not_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralRanking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('year', models.PositiveIntegerField(help_text='Año del ranking')),
                ('month', models.PositiveIntegerField(help_text='Mes del ranking (1-12)')),
                ('referral_reservations_count', models.PositiveIntegerField(default=0, help_text='Cantidad de reservas hechas por referidos en este mes')),
                ('total_referral_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total facturado por reservas de referidos en soles', max_digits=10)),
                ('referrals_made_count', models.PositiveIntegerField(default=0, help_text='Cantidad de nuevos referidos en este mes')),
                ('position', models.PositiveIntegerField(blank=True, help_text='Posición en el ranking mensual (1 = primer lugar)', null=True)),
                ('points_earned', models.DecimalField(decimal_places=2, default=0, help_text='Puntos ganados por referidos este mes', max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rankings', to='clients.clients')),
            ],
            options={
                'verbose_name': 'Ranking Mensual de Referidos',
                'verbose_name_plural': 'Ranking Mensual de Referidos',
                'ordering': ['-year', '-month', 'position'],
                'unique_together': {('client', 'year', 'month')},
            },
        ),
    ]
