# Generated by Django 4.2.11 on 2025-10-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0021_add_referral_ranking_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpoints',
            name='transaction_type',
            field=models.CharField(choices=[('earned', 'Puntos Ganados'), ('redeemed', 'Puntos Canjeados'), ('expired', 'Puntos Expirados'), ('refunded', 'Puntos Devueltos'), ('referral', 'Puntos por Referido'), ('manual', 'Ajuste Manual')], max_length=8),
        ),
    ]
