# Generated by Django 4.2.11 on 2025-10-06 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0022_add_manual_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpoints',
            name='transaction_type',
            field=models.CharField(choices=[('earned', 'Bonificación de puntos'), ('redeemed', 'Redención de puntos'), ('expired', 'Puntos Expirados'), ('refunded', 'Puntos Devueltos'), ('referral', 'Puntos por Referido')], max_length=8),
        ),
    ]
