# Generated by Django 4.2.11 on 2025-11-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0023_update_transaction_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='welcome_discount_issued',
            field=models.BooleanField(default=False, help_text='Indica si ya se le emitió un código de descuento de bienvenida'),
        ),
        migrations.AddField(
            model_name='clients',
            name='welcome_discount_issued_at',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se emitió el código de bienvenida', null=True),
        ),
    ]
