# Generated by Django 4.2.11 on 2025-11-26 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0025_add_push_token_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPushToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('expo_token', models.CharField(help_text='Token Expo Push (ExponentPushToken[xxx])', max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], default='android', help_text='Tipo de dispositivo', max_length=10)),
                ('device_name', models.CharField(blank=True, help_text='Nombre del dispositivo (opcional)', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Token activo para recibir notificaciones')),
                ('last_used', models.DateTimeField(blank=True, help_text='Última vez que se envió una notificación', null=True)),
                ('failed_attempts', models.PositiveIntegerField(default=0, help_text='Intentos fallidos consecutivos')),
                ('user', models.ForeignKey(help_text='Usuario administrador propietario del dispositivo', on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Push Administrador',
                'verbose_name_plural': 'Tokens Push Administradores',
                'ordering': ['-created'],
            },
        ),
    ]
