# Generated by Django 4.2.11 on 2025-11-26 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0026_adminpushtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='When the instance was created.', verbose_name='created at')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The last time at the instance was modified.', verbose_name='updated at')),
                ('deleted', models.BooleanField(default=False, help_text='It can be set to false, usefull to simulate deletion')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('body', models.TextField(verbose_name='Cuerpo')),
                ('notification_type', models.CharField(help_text='Ej: reservation_created, payment_approved, admin_reservation_created, etc.', max_length=50, verbose_name='Tipo de Notificación')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Datos JSON enviados con la notificación', verbose_name='Datos Adicionales')),
                ('expo_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Expo')),
                ('device_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Dispositivo')),
                ('success', models.BooleanField(default=False, verbose_name='Enviado Exitosamente')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('read', models.BooleanField(default=False, verbose_name='Leída')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Leída el')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada el')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='clients.clients', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['client', '-sent_at'], name='clients_not_client__75b749_idx'), models.Index(fields=['admin', '-sent_at'], name='clients_not_admin_i_5b1b53_idx'), models.Index(fields=['notification_type', '-sent_at'], name='clients_not_notific_ec3f3b_idx'), models.Index(fields=['read', '-sent_at'], name='clients_not_read_28b53d_idx'), models.Index(fields=['success', '-sent_at'], name='clients_not_success_58280d_idx')],
            },
        ),
    ]
